A bunch of front shit
rubenvoss/GoClimb pull request #127
Opened 2022-09-23 10:01 UTC by brogergvhs

a bit of chatroom frontend changes + text me button

2022-09-23 10:10 UTC, brogergvhs commented
![image](https://user-images.githubusercontent.com/36773220/191938886-f266d60b-3e3e-4a25-bcbd-19b782023346.png)

2022-09-23 10:21 UTC, rubenvoss requested changes

2022-09-23 10:21 UTC, rubenvoss commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Sign up", new_registration_path(resource_name)  %><br />
pls remove extra space

2022-09-29 14:20 UTC, rubenvoss approved these changes

2022-09-29 14:43 UTC, merged